### ISSUE TITLE
"TypeError: undefined is not a function" when adding new password entry

### ISSUE THREAD

**Issue by purpleplatypus** [devgeeks/Encryptr#133]
I ran into this issue the other day on version 1.1.0 for OS X.
After entering my master password wrong a couple of times (maybe 3 times), and then finally getting it right, I tried to create a new password entry. Clicked on the plus button followed by the password option, and got the following lovely error:

Uncaught Node.js error
TypeError: undefined is not a function
    at Backbone.View.extend.a_clickHandler (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/Encryptr.js:727:11)
    at HTMLDivElement.delegator (file:///Applications/Encryptr.app/Contents/Resources/app.nw/components/zepto/zepto.js:1824:43)
    at HTMLDivElement.handler.proxy (file:///Applications/Encryptr.app/Contents/Resources/app.nw/components/zepto/zepto.js:1699:31)

I'm not sure if this is a bug in Node.js or in how it's being called, but I figured I would file an issue.

**Comment by helveticade** [comment]
This and #148 are the same issue. It's _probably_ fixed but please reopen this if it crops up again.
