### ISSUE TITLE
Error message when left open Encryptr for 2 hours

### ISSUE THREAD

**Issue by participante0** [devgeeks/Encryptr#142]
It happened more than 6 times in Windows 7 and Linux Mint 17, both with Encryptr 1.1.0.

I use Encryptr two minutes, I log off, leave the program opened with the PC turned on. Back at 2 hours (approximately) and I see these messages:

In Linux:
```
Uncaught node.js Error

Error: Popping from an empty stack!
    at popAll (file:///tmp/.org.chromium.Chromium.pwsJbh/components/backstack/backstack.js:775:48)
    at Backbone.View.extend.popAll (file:///tmp/.org.chromium.Chromium.pwsJbh/components/backstack/backstack.js:971:59)
    at eval (file:///tmp/.org.chromium.Chromium.pwsJbh/js/Encryptr.js:1532:38)
```

In Windows:
```
Uncaught node.js Error 

Error: Popping from an empty stack!
    at popAll (file:///C:/Users/participante/AppData/Local/Temp/nw1856_3609/components/backstack/backstack.js:775:48)
    at Backbone.View.extend.popAll (file:///C:/Users/participante/AppData/Local/Temp/nw1856_3609/components/backstack/backstack.js:971:59)
    at eval (file:///C:/Users/participante/AppData/Local/Temp/nw1856_3609/js/Encryptr.js:1532:38)
```

**Comment by devgeeks** [comment]
Thanks.. I appreciate the repro steps. I'll look into it now.

**Comment by devgeeks** [comment]
I think I know what this is... I think it will be fixed in the next version (1.2.0).

**Comment by helveticade** [comment]
Thanks, @participante0, pretty sure this is ready to go.

**Comment by devgeeks** [comment]
Re-open this if it still happens after 1.2.0 is released.

**Comment by devgeeks** [comment]
Closed too early.

However, I think I *have* finally found it and fixed it.
