### ISSUE TITLE
"TypeError: Cannot call method 'push' of undefined" when trying to edit a password entry

### ISSUE THREAD

**Issue by participante0** [devgeeks/Encryptr#148]
Encryptr 1.1.0 debian package (at least). Steps to reproduce it:
- Click on a password entry.
- Click on the EDIT button before it finishes loading the content. (You need to be fast or use a slow computer).

```
Uncaught node.js Error 

TypeError: Cannot call method 'push' of undefined
    at Backbone.View.extend.initialize (file:///tmp/.org.chromium.Chromium.d0ZIUt/js/Encryptr.js:964:15)
    at Backbone.View (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backbone/backbone.js:1001:21)
    at new child (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backbone/backbone.js:1566:41)
    at replaceView (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backstack/backstack.js:803:43)
    at Backbone.View.extend.replaceView (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backstack/backstack.js:985:64)
    at Backbone.View.extend.editButton_clickHandler (file:///tmp/.org.chromium.Chromium.d0ZIUt/js/Encryptr.js:1350:28)
    at eval (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backbone/backbone.js:100:18)
    at eval (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/underscore/underscore.js:724:19)
    at triggerEvents (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backbone/backbone.js:206:57)
    at Backbone.Events.trigger (file:///tmp/.org.chromium.Chromium.d0ZIUt/components/backbone/backbone.js:148:19)
```

**Comment by devgeeks** [comment]
Thanks. Looks like I might need to disable the edit button until it has finished loading.

**Comment by participante0** [comment]
Thanks for your work on it.

Also happens in Windows.

In the Android app, after touching the edit button, I can't go back to the main screen and I need to clear the cache of the app to use it again.

**Comment by helveticade** [comment]
This issue will be fixed in 3.0.
