### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mstarkie** [devgeeks/Encryptr#165]
Uncaught node.js Error 
Started Encryptr
Added a General entry
Saved the changes
Tried to add a second entry:

TypeError: undefined is not a function
    at Backbone.View.extend.a_clickHandler (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/Encryptr.js:727:11)
    at HTMLDivElement.delegator (file:///Applications/Encryptr.app/Contents/Resources/app.nw/components/zepto/zepto.js:1824:43)
    at HTMLDivElement.handler.proxy (file:///Applications/Encryptr.app/Contents/Resources/app.nw/components/zepto/zepto.js:1699:31)

Version 1.1.0 (1.1.0)
MacBook Air
Mac OS version 10.10.3

**Comment by helveticade** [comment]
@mstarkie we havent had any luck reproducing this but will keep looking into it. Have you had it reoccur since?

**Comment by Yahkem** [comment]
This occurs to me when I click directly on the image (e.g. the key next to 'Password') on the 'add new' menu (top right). The left menu (About, Settings, Log out) is working fine.

v1.2.0
Windows 8.1 Home 64-bit

**Comment by devgeeks** [comment]
Ah. I can reproduce this now.

Thanks, I'll get onto this...

**Comment by devgeeks** [comment]
Got it..
